"""add task fields

Revision ID: 0e334dc29223
Revises: 81cf5e7f305e
Create Date: 2026-04-09 02:27:48.987124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e334dc29223'
down_revision: Union[str, Sequence[str], None] = '81cf5e7f305e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    op.create_check_constraint(
    "check_priority_range",
    "tasks",
    "priority >= 1 AND priority <= 3"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_priority_range", "tasks", type_="check")
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###

