"""change due_date from datetime to date

Revision ID: 821b871b435e
Revises: 0e334dc29223
Create Date: 2026-04-09 05:14:13.167437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '821b871b435e'
down_revision: Union[str, Sequence[str], None] = '0e334dc29223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               postgresql_using="due_date::date",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="due_date::timestamp",
               existing_nullable=True)
    # ### end Alembic commands ###
